/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triaudio.view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import triaudio.DAO.ctrlTestes;
import triaudio.users.usuarios_Pacientes;

/**
 *
 * @author felip
 */
public class Testes extends javax.swing.JFrame {

    /**
     * Creates new form Testes
     */
   
    public Testes() {
        initComponents();
        setIcon();
    }
public void Eportarcpf (usuarios_Pacientes cpf){
    cpfTeste.setText(cpf.getCpfResponsavelP());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Teste1 = new javax.swing.ButtonGroup();
        RetesteEOAE = new javax.swing.ButtonGroup();
        RetestePeate = new javax.swing.ButtonGroup();
        Diagnostico = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cpfTeste = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        PassaT1 = new javax.swing.JRadioButton();
        FalhaT1 = new javax.swing.JRadioButton();
        passaT = new javax.swing.JRadioButton();
        FalhaT = new javax.swing.JRadioButton();
        PassaREOAE = new javax.swing.JRadioButton();
        FalhaREOAE = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        PassaSRiscoR = new javax.swing.JRadioButton();
        FalhaRPEATE = new javax.swing.JRadioButton();
        PassaCRiscoR = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        FalsoPositivoSR = new javax.swing.JRadioButton();
        confirmado = new javax.swing.JRadioButton();
        FalsoPositivoCR = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TerapiaFonodiologicaORL = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RehabilitacaoImplateCoclear = new javax.swing.JTextField();
        IndicadordeRisco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SequimentoORl = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        RehabilitacaoAasi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Identificação De Risco Para Deficiência Auditiva");

        jLabel2.setText("Teste EOAE - Sem irda:");

        jLabel3.setText("Teste PEATE - Com irda:");

        salvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salvar.setText("Salvar");
        salvar.setEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF do Responsavel:");

        try {
            cpfTeste.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfTeste.setEnabled(false);

        jLabel5.setText("Reteste EOAE:");
        jLabel5.setEnabled(false);

        jScrollPane1.setEnabled(false);

        texto.setEnabled(false);
        jScrollPane1.setViewportView(texto);

        jLabel6.setText("Descrição do texto:");
        jLabel6.setEnabled(false);

        Teste1.add(PassaT1);
        PassaT1.setActionCommand("Passa- EOAE - SemIrda");
        PassaT1.setText("Passa");
        PassaT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaT1ActionPerformed(evt);
            }
        });

        Teste1.add(FalhaT1);
        FalhaT1.setActionCommand("Falha-EOAE-SemIrda");
        FalhaT1.setText("Falha");
        FalhaT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalhaT1ActionPerformed(evt);
            }
        });

        Teste1.add(passaT);
        passaT.setActionCommand("Passa-PEATE-ComIrda");
        passaT.setText("Passa");
        passaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passaTActionPerformed(evt);
            }
        });

        Teste1.add(FalhaT);
        FalhaT.setActionCommand("Falha-PEATE-ComIrda");
        FalhaT.setText("Falha");
        FalhaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalhaTActionPerformed(evt);
            }
        });

        RetesteEOAE.add(PassaREOAE);
        PassaREOAE.setActionCommand("Passa-RetesteEOAE");
        PassaREOAE.setText("Passa");
        PassaREOAE.setEnabled(false);
        PassaREOAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaREOAEActionPerformed(evt);
            }
        });

        RetesteEOAE.add(FalhaREOAE);
        FalhaREOAE.setActionCommand("Falha-RetesteEOAE");
        FalhaREOAE.setText("Falha");
        FalhaREOAE.setEnabled(false);
        FalhaREOAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalhaREOAEActionPerformed(evt);
            }
        });

        jLabel7.setText("Reteste PEATE:");
        jLabel7.setEnabled(false);

        RetestePeate.add(PassaSRiscoR);
        PassaSRiscoR.setActionCommand("Passa Sem Risco");
        PassaSRiscoR.setText("Passa Sem Risco");
        PassaSRiscoR.setEnabled(false);
        PassaSRiscoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaSRiscoRActionPerformed(evt);
            }
        });

        RetestePeate.add(FalhaRPEATE);
        FalhaRPEATE.setActionCommand("Falha");
        FalhaRPEATE.setText("Falha");
        FalhaRPEATE.setEnabled(false);
        FalhaRPEATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalhaRPEATEActionPerformed(evt);
            }
        });

        RetestePeate.add(PassaCRiscoR);
        PassaCRiscoR.setActionCommand("Passa com Risco");
        PassaCRiscoR.setText("Passa Com Risco");
        PassaCRiscoR.setEnabled(false);
        PassaCRiscoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaCRiscoRActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Diagnostico Otorrinolaringológico e  Audiologico");
        jLabel8.setEnabled(false);

        Diagnostico.add(FalsoPositivoSR);
        FalsoPositivoSR.setActionCommand("Falso Positivo Sem Risco");
        FalsoPositivoSR.setText("Falso Positivo Sem Risco");
        FalsoPositivoSR.setEnabled(false);
        FalsoPositivoSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalsoPositivoSRActionPerformed(evt);
            }
        });

        Diagnostico.add(confirmado);
        confirmado.setActionCommand("Confirmado");
        confirmado.setText("Confirmado");
        confirmado.setEnabled(false);
        confirmado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmadoActionPerformed(evt);
            }
        });

        Diagnostico.add(FalsoPositivoCR);
        FalsoPositivoCR.setActionCommand("Falso Positivo Com Risco");
        FalsoPositivoCR.setText("Falso Positivo Com Risco");
        FalsoPositivoCR.setEnabled(false);
        FalsoPositivoCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalsoPositivoCRActionPerformed(evt);
            }
        });

        jLabel9.setText("Dados dos Testes: ");
        jLabel9.setEnabled(false);

        jLabel10.setText("Terapia Fonodiologica ORL:");
        jLabel10.setEnabled(false);

        TerapiaFonodiologicaORL.setEnabled(false);

        jLabel11.setText("(Re)habilitação Implante Coclear:");
        jLabel11.setEnabled(false);

        RehabilitacaoImplateCoclear.setEnabled(false);

        IndicadordeRisco.setEnabled(false);
        IndicadordeRisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndicadordeRiscoActionPerformed(evt);
            }
        });

        jLabel13.setText("Indicador de Risco:");
        jLabel13.setEnabled(false);

        jLabel14.setText("Sequimento ORL:");
        jLabel14.setEnabled(false);

        SequimentoORl.setEnabled(false);

        jLabel15.setText("(Re)habilitação Aasi:");
        jLabel15.setEnabled(false);

        RehabilitacaoAasi.setEnabled(false);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PassaREOAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FalhaREOAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(197, 197, 197))
                    .addComponent(jScrollPane1))
                .addGap(681, 681, 681))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(98, 98, 98))
                                    .addComponent(cpfTeste))
                                .addGap(699, 699, 699))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(343, 343, 343))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PassaT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FalhaT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(388, 388, 388)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(149, 149, 149))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(331, 331, 331))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(passaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FalhaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(303, 303, 303))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PassaSRiscoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FalhaRPEATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PassaCRiscoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(144, 144, 144))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(315, 315, 315))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(FalsoPositivoSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(confirmado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(93, 93, 93))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(64, 64, 64))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(125, 125, 125))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(RehabilitacaoAasi, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TerapiaFonodiologicaORL, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(RehabilitacaoImplateCoclear, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(24, 24, 24)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IndicadordeRisco)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(60, 60, 60))
                                                    .addComponent(FalsoPositivoCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(51, 51, 51)))
                                                .addGap(38, 38, 38))
                                            .addComponent(SequimentoORl)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(911, 911, 911)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpfTeste)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassaT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FalhaT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FalhaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassaREOAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FalhaREOAE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PassaSRiscoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FalhaRPEATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PassaCRiscoR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FalsoPositivoSR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FalsoPositivoCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TerapiaFonodiologicaORL)
                            .addComponent(IndicadordeRisco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RehabilitacaoImplateCoclear)
                            .addComponent(SequimentoORl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RehabilitacaoAasi)))
                .addGap(2, 2, 2)
                .addComponent(salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

    usuarios_Pacientes tes = new usuarios_Pacientes();  
tes.setCpfTeste(cpfTeste.getText());
try{
    Teste1.getSelection().getActionCommand();
    tes.setTeste1(Teste1.getSelection().getActionCommand());
} catch (Exception e){
   tes.setTeste1("");
   
}
try{
    RetesteEOAE.getSelection().getActionCommand();
    tes.setRetesteEOAE(RetesteEOAE.getSelection().getActionCommand());
} catch (Exception e){
   tes.setRetesteEOAE("");
}
try{
    RetestePeate.getSelection().getActionCommand();
    tes.setRetestePeate(RetestePeate.getSelection().getActionCommand());
}catch(Exception e){
    tes.setRetestePeate("");
}
try{
    Diagnostico.getSelection().getActionCommand();
    tes.setDiagnostico(Diagnostico.getSelection().getActionCommand());
}catch(Exception e){
    tes.setDiagnostico("");
}
tes.setTexto(texto.getText());
tes.setRehabilitacaoImplateCoclear(RehabilitacaoImplateCoclear.getText());
tes.setRehabilitacaoAasi(RehabilitacaoAasi.getText());
tes.setSequimentoORl(SequimentoORl.getText());
tes.setIndicadordeRisco(IndicadordeRisco.getText());
tes.setTerapiaFonodiologicaORL(TerapiaFonodiologicaORL.getText());
ctrlTestes te = new ctrlTestes();
te.salvarteste(tes);
Telapricipal volta = new Telapricipal ();
                         volta.setVisible(true);
                         dispose();
    


// TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    private void FalhaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalhaTActionPerformed
salvar.setEnabled(true);
//EOAE
jLabel5.setEnabled(false);
PassaREOAE.setEnabled(false);
FalhaREOAE.setEnabled(false);
jLabel6.setEnabled(false);
texto.setEnabled(false);
//Peate
jLabel7.setEnabled(true);
PassaSRiscoR.setEnabled(true);
FalhaRPEATE.setEnabled(true);
PassaCRiscoR.setEnabled(true);
    }//GEN-LAST:event_FalhaTActionPerformed

    private void FalsoPositivoSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalsoPositivoSRActionPerformed
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_FalsoPositivoSRActionPerformed

    private void IndicadordeRiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndicadordeRiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndicadordeRiscoActionPerformed

    private void FalhaT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalhaT1ActionPerformed
jLabel5.setEnabled(true);
PassaREOAE.setEnabled(true);
FalhaREOAE.setEnabled(true);
jLabel6.setEnabled(true);
texto.setEnabled(true);
//peate
jLabel7.setEnabled(false);
PassaSRiscoR.setEnabled(false);
FalhaRPEATE.setEnabled(false);
PassaCRiscoR.setEnabled(false);
//
jLabel8.setEnabled(false);
FalsoPositivoSR.setEnabled(false);
confirmado.setEnabled(false);
FalsoPositivoCR.setEnabled(false);

// TODO add your handling code here:
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);
salvar.setEnabled(true);
    }//GEN-LAST:event_FalhaT1ActionPerformed

    private void PassaT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaT1ActionPerformed
jLabel5.setEnabled(false);
PassaREOAE.setEnabled(false);
FalhaREOAE.setEnabled(false);
jLabel6.setEnabled(false);
texto.setEnabled(false);
//peate
jLabel7.setEnabled(false);
PassaSRiscoR.setEnabled(false);
FalhaRPEATE.setEnabled(false);
PassaCRiscoR.setEnabled(false);
//
jLabel8.setEnabled(false);
FalsoPositivoSR.setEnabled(false);
confirmado.setEnabled(false);
FalsoPositivoCR.setEnabled(false);
// TODO add your handling code here:
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);

salvar.setEnabled(true);
    }//GEN-LAST:event_PassaT1ActionPerformed

    private void passaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passaTActionPerformed
salvar.setEnabled(true);
jLabel5.setEnabled(false);
PassaREOAE.setEnabled(false);
FalhaREOAE.setEnabled(false);
jLabel6.setEnabled(false);
texto.setEnabled(false);
//peate
jLabel7.setEnabled(false);
PassaSRiscoR.setEnabled(false);
FalhaRPEATE.setEnabled(false);
PassaCRiscoR.setEnabled(false);
//
jLabel8.setEnabled(false);
FalsoPositivoSR.setEnabled(false);
confirmado.setEnabled(false);
FalsoPositivoCR.setEnabled(false);
// TODO add your handling code here:
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);
    }//GEN-LAST:event_passaTActionPerformed

    private void FalhaREOAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalhaREOAEActionPerformed
//peate
jLabel7.setEnabled(true);
PassaSRiscoR.setEnabled(true);
FalhaRPEATE.setEnabled(true);
PassaCRiscoR.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_FalhaREOAEActionPerformed

    private void PassaREOAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaREOAEActionPerformed
//peate
jLabel7.setEnabled(false);
PassaSRiscoR.setEnabled(false);
FalhaRPEATE.setEnabled(false);
PassaCRiscoR.setEnabled(false);
// TODO add your handling code here:
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);
    }//GEN-LAST:event_PassaREOAEActionPerformed

    private void FalhaRPEATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalhaRPEATEActionPerformed
jLabel8.setEnabled(true);
FalsoPositivoSR.setEnabled(true);
confirmado.setEnabled(true);
FalsoPositivoCR.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_FalhaRPEATEActionPerformed

    private void FalsoPositivoCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalsoPositivoCRActionPerformed
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);    }//GEN-LAST:event_FalsoPositivoCRActionPerformed

    private void PassaSRiscoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaSRiscoRActionPerformed
jLabel8.setEnabled(false);
FalsoPositivoSR.setEnabled(false);
confirmado.setEnabled(false);
FalsoPositivoCR.setEnabled(false);
// TODO add your handling code here:
TerapiaFonodiologicaORL.setEnabled(false);
IndicadordeRisco.setEnabled(false);
RehabilitacaoImplateCoclear.setEnabled(false);
SequimentoORl.setEnabled(false);
RehabilitacaoAasi.setEnabled(false);
jLabel9.setEnabled(false);
jLabel10.setEnabled(false);
jLabel11.setEnabled(false);
jLabel15.setEnabled(false);
jLabel13.setEnabled(false);
jLabel14.setEnabled(false);
    }//GEN-LAST:event_PassaSRiscoRActionPerformed

    private void PassaCRiscoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaCRiscoRActionPerformed
jLabel8.setEnabled(false);
FalsoPositivoSR.setEnabled(false);
confirmado.setEnabled(false);
FalsoPositivoCR.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_PassaCRiscoRActionPerformed

    private void confirmadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmadoActionPerformed
TerapiaFonodiologicaORL.setEnabled(true);
IndicadordeRisco.setEnabled(true);
RehabilitacaoImplateCoclear.setEnabled(true);
SequimentoORl.setEnabled(true);
RehabilitacaoAasi.setEnabled(true);
jLabel9.setEnabled(true);
jLabel10.setEnabled(true);
jLabel11.setEnabled(true);
jLabel15.setEnabled(true);
jLabel13.setEnabled(true);
jLabel14.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Diagnostico;
    private javax.swing.JRadioButton FalhaREOAE;
    private javax.swing.JRadioButton FalhaRPEATE;
    private javax.swing.JRadioButton FalhaT;
    private javax.swing.JRadioButton FalhaT1;
    private javax.swing.JRadioButton FalsoPositivoCR;
    private javax.swing.JRadioButton FalsoPositivoSR;
    private javax.swing.JTextField IndicadordeRisco;
    private javax.swing.JRadioButton PassaCRiscoR;
    private javax.swing.JRadioButton PassaREOAE;
    private javax.swing.JRadioButton PassaSRiscoR;
    private javax.swing.JRadioButton PassaT1;
    private javax.swing.JTextField RehabilitacaoAasi;
    private javax.swing.JTextField RehabilitacaoImplateCoclear;
    private javax.swing.ButtonGroup RetesteEOAE;
    private javax.swing.ButtonGroup RetestePeate;
    private javax.swing.JTextField SequimentoORl;
    private javax.swing.JTextField TerapiaFonodiologicaORL;
    private javax.swing.ButtonGroup Teste1;
    private javax.swing.JRadioButton confirmado;
    private javax.swing.JFormattedTextField cpfTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton passaT;
    private javax.swing.JButton salvar;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
private void limpaCampos(){
    
}
private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png"))); }
}
